# Generated by Django 5.1.7 on 2025-04-02 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.JSONField(blank=True, default=dict, help_text='Structure: {"top": [], "middle": [], "base": []}')),
                ('pricePerML', models.DecimalField(decimal_places=2, help_text='Price per milliliter', max_digits=6)),
                ('thumbnailUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('fullSizeUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('gender', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('unisex', 'Unisex')], max_length=10)),
                ('accords', models.ManyToManyField(blank=True, related_name='perfumes', to='api.accord')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfumes', to='api.brand')),
                ('occasions', models.ManyToManyField(blank=True, related_name='perfumes', to='api.occasion')),
            ],
        ),
    ]
