# Generated by Django 5.1.7 on 2025-04-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_surveyresponse_userperfumematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='best_for',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='country_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from the source CSV', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='longevity_rating',
            field=models.FloatField(blank=True, help_text='Longevity rating (0-1) from source', null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='overall_rating',
            field=models.FloatField(blank=True, help_text='Overall rating from source', null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price_value_rating',
            field=models.FloatField(blank=True, help_text='Price/Value rating (0-1) from source', null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='rating_count',
            field=models.IntegerField(default=0, help_text='Number of ratings from source'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='recommended_perfume_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of external_ids of recommended perfumes'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='season',
            field=models.CharField(blank=True, choices=[('winter', 'Winter'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('spring', 'Spring')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='sillage_rating',
            field=models.FloatField(blank=True, help_text='Sillage rating (0-1) from source', null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='similar_perfume_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of external_ids of similar perfumes'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='year_released',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unisex', 'Unisex')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='price_per_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per milliliter', max_digits=6, null=True),
        ),
    ]
