# Generated by Django 5.1.7 on 2025-04-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_perfume_best_for_perfume_country_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='notes',
        ),
        migrations.AddField(
            model_name='perfume',
            name='base_notes',
            field=models.JSONField(blank=True, default=list, help_text='List of base note names'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='middle_notes',
            field=models.JSONField(blank=True, default=list, help_text='List of middle note names'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='popularity',
            field=models.IntegerField(default=0, help_text='Popularity score based on recent magnitude'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='top_notes',
            field=models.JSONField(blank=True, default=list, help_text='List of top note names'),
        ),
    ]
