# Generated by Django 5.1.7 on 2025-04-08 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_perfume_notes_perfume_base_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('perfume', 'Perfume'), ('box', 'Box')], default='perfume', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('decant_size', models.IntegerField(blank=True, help_text='Size of decant in ML, if applicable', null=True)),
                ('price_at_addition', models.DecimalField(decimal_places=2, max_digits=10)),
                ('box_configuration', models.JSONField(blank=True, help_text='JSON configuration for custom boxes', null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.cart')),
                ('perfume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.perfume')),
            ],
        ),
    ]
