# Generated by Django 5.1.7 on 2025-04-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('perfumes', models.ManyToManyField(blank=True, related_name='predefined_boxes', to='api.perfume')),
            ],
        ),
    ]
