# Generated by Django 5.2 on 2025-04-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_favorite_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedbox',
            name='name',
        ),
        migrations.AddField(
            model_name='predefinedbox',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], help_text='Target gender for the box', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='predefinedbox',
            name='icon',
            field=models.CharField(blank=True, help_text='Feather icon name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='predefinedbox',
            name='title',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
