# Generated by Django 5.2 on 2025-04-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_predefinedbox_name_predefinedbox_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('gender', 'Gender Selection'), ('accord', 'Accord Preference')], max_length=20)),
                ('text', models.CharField(help_text='The question text presented to the user.', max_length=255)),
                ('options', models.JSONField(blank=True, help_text="JSON defining options (e.g., for gender: [{'id': 'male', 'label': 'Masculinas', 'emoji': '👨'}])", null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the question appears in the survey.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is currently used in the survey.')),
                ('accord', models.ForeignKey(blank=True, help_text="Associated accord, if question_type is 'accord'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='api.accord')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
