# Generated by Django 5.2 on 2025-04-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_surveyquestion'),
    ]

    operations = [
        # 1. Create Note model
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),

        # 2. Add ManyToMany fields with different names (not replacing existing fields yet)
        migrations.AddField(
            model_name='perfume',
            name='top_notes_m2m',
            field=models.ManyToManyField(blank=True, related_name='perfumes_as_top', to='api.note'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='middle_notes_m2m',
            field=models.ManyToManyField(blank=True, related_name='perfumes_as_middle', to='api.note'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='base_notes_m2m',
            field=models.ManyToManyField(blank=True, related_name='perfumes_as_base', to='api.note'),
        ),

        # 3. Data migration will be handled via custom command after migration is applied
    ]
