# Generated by Django 5.2 on 2025-04-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20250418_1623'),
    ]

    # SQL-based migration to manually rename the through tables while preserving data

    operations = [
        # This migration just performs SQL operations to rename the through tables
        # while keeping all data intact

        migrations.RunSQL(
            # Forward SQL - rename tables and update constraints
            [
                # Rename the through table from [app]_perfume_top_notes_m2m to [app]_perfume_top_notes
                'ALTER TABLE api_perfume_top_notes_m2m RENAME TO api_perfume_top_notes;',
                # Rename the through table from [app]_perfume_middle_notes_m2m to [app]_perfume_middle_notes
                'ALTER TABLE api_perfume_middle_notes_m2m RENAME TO api_perfume_middle_notes;',
                # Rename the through table from [app]_perfume_base_notes_m2m to [app]_perfume_base_notes
                'ALTER TABLE api_perfume_base_notes_m2m RENAME TO api_perfume_base_notes;',
            ],
            # Reverse SQL - revert the renames
            [
                'ALTER TABLE api_perfume_top_notes RENAME TO api_perfume_top_notes_m2m;',
                'ALTER TABLE api_perfume_middle_notes RENAME TO api_perfume_middle_notes_m2m;',
                'ALTER TABLE api_perfume_base_notes RENAME TO api_perfume_base_notes_m2m;',
            ]
        ),
    ]
