# Generated by Django 5.2 on 2025-04-18 16:27

from django.db import migrations


def rename_tables_if_exist(apps, schema_editor):
    """Rename m2m tables only if they exist (for existing databases)"""
    with schema_editor.connection.cursor() as cursor:
        # Check and rename top_notes table
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'api_perfume_top_notes_m2m'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE api_perfume_top_notes_m2m RENAME TO api_perfume_top_notes;')

        # Check and rename middle_notes table
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'api_perfume_middle_notes_m2m'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE api_perfume_middle_notes_m2m RENAME TO api_perfume_middle_notes;')

        # Check and rename base_notes table
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'api_perfume_base_notes_m2m'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE api_perfume_base_notes_m2m RENAME TO api_perfume_base_notes;')


def reverse_rename_tables(apps, schema_editor):
    """Reverse the rename operation"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'api_perfume_top_notes'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE api_perfume_top_notes RENAME TO api_perfume_top_notes_m2m;')

        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'api_perfume_middle_notes'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE api_perfume_middle_notes RENAME TO api_perfume_middle_notes_m2m;')

        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_name = 'api_perfume_base_notes'
            );
        """)
        if cursor.fetchone()[0]:
            cursor.execute('ALTER TABLE api_perfume_base_notes RENAME TO api_perfume_base_notes_m2m;')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20250418_1623'),
    ]

    operations = [
        migrations.RunPython(rename_tables_if_exist, reverse_rename_tables),
    ]
