# Generated by Django 5.2 on 2025-04-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_perfume_base_notes_m2m_and_more'),
    ]

    operations = [
        # Keep only the operations to remove the obsolete JSONField columns
        migrations.RemoveField(
            model_name='perfume',
            name='base_notes', # This was the old JSONField
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='middle_notes', # This was the old JSONField
        ),
        migrations.RemoveField(
            model_name='perfume',
            name='top_notes', # This was the old JSONField
        ),
        # Remove other incorrect/unnecessary operations generated automatically
    ]
