# Generated by Django 5.2 on 2025-04-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_perfume_base_notes_m2m_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfume',
            old_name='base_notes_m2m',
            new_name='base_notes',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='middle_notes_m2m',
            new_name='middle_notes',
        ),
        migrations.RenameField(
            model_name='perfume',
            old_name='top_notes_m2m',
            new_name='top_notes',
        ),
        migrations.AlterField(
            model_name='perfume',
            name='best_for',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('night', 'Night'), ('both', 'Day and Night')], max_length=5, null=True),
        ),
    ]
