# Generated by Django 5.2 on 2025-04-30 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_base_notes_m2m_perfume_base_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeAccordOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('accord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accord')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perfume')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('perfume', 'accord')},
            },
        ),
    ]
