# Generated by Django 5.2 on 2025-04-30 03:35
# Manual migration step 2/3 for introducing through model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_perfumeaccordorder_alter_perfume_accords'), # Depends on the creation of the through model
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='accords',
        ),
    ]