# Generated by Django 5.2 on 2025-04-30 03:36
# Manual migration step 3/3 for introducing through model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_perfume_accords'), # Depends on the removal of the old field
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='accords',
            field=models.ManyToManyField(
                blank=True,
                related_name='perfumes',
                through='api.PerfumeAccordOrder',
                to='api.accord'
            ),
        ),
    ]