# Generated by Django 5.2 on 2025-05-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_perfume_accords_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='User-facing code (e.g., SUMMER10). Should be stored in uppercase.', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value (e.g., 10 for 10% or 5000 for $5000 CLP)', max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_purchase_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum cart total required to apply', max_digits=10, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiry date and time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the coupon is currently active')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used in total', null=True)),
                ('uses_count', models.PositiveIntegerField(default=0, help_text='How many times this coupon has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
