# Generated by Django 5.2 on 2025-05-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, help_text="Name of the item (e.g., perfume name or box name like 'AI Box (4 x 5ml)')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='box_configuration',
            field=models.JSONField(blank=True, help_text='JSON configuration for boxes (e.g., list of perfumes, specific decant size for the box)', null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='decant_size',
            field=models.IntegerField(blank=True, help_text='Size of decant in ML (for individual perfumes or items in a box)', null=True),
        ),
    ]
